<section <?php if(empty($_GET['context']) || $_GET['context'] !== 'edit') echo get_block_wrapper_attributes( array('class' => "py-32 px-6 bg-bone-200", 'data-block-name' => "space-gallery", ) ); else echo 'data-wp-block-props="true"'; ?>>
    <div class="max-w-7xl mx-auto w-full">
        <h2 class="font-sans uppercase text-[0.75rem] tracking-[0.15em] font-medium text-charcoal-600 text-center mb-20"><?php echo PG_Blocks_v4::getAttribute( $args, 'section_title' ) ?></h2>
        <div class="grid md:grid-cols-2 gap-8">
            <div class="aspect-[4/5] bg-mist-300 bg-[url('https://images.unsplash.com/photo-1640348307767-b8e8bc765ff5?ixid=M3wyMDkyMnwwfDF8c2VhcmNofDE4fHxpbnRlcmlvciUyMGxpbmVufGVufDB8fHx8MTc3MzA2NTg0MXww&ixlib=rb-4.1.0q=85&fm=jpg&crop=faces&cs=srgb&w=1200&h=800&fit=crop')] bg-cover bg-center opacity-0 [animation:fadeInScale_1s_ease-out_forwards] [animation-timeline:view()] [animation-range:entry_0%_entry_40%]" style=";<?php echo ( PG_Blocks_v4::getImageUrl( $args, 'image_1', 'full' ) ? ( 'background-image: url('.PG_Blocks_v4::getImageUrl( $args, 'image_1', 'full' ).')' ) : '' ); ?>"></div>
            <div class="aspect-[4/5] bg-mist-300 bg-[url('https://images.unsplash.com/photo-1520682464353-63a64fa8bf98?ixid=M3wyMDkyMnwwfDF8c2VhcmNofDE4fHxmb3Jlc3QlMjBwYXRofGVufDB8fHx8MTc3MzA2NTg0Mnww&ixlib=rb-4.1.0q=85&fm=jpg&crop=faces&cs=srgb&w=1200&h=800&fit=crop')] bg-cover bg-center opacity-0 [animation:fadeInScale_1s_ease-out_forwards] [animation-timeline:view()] [animation-range:entry_0%_entry_40%]" style=";<?php echo ( PG_Blocks_v4::getImageUrl( $args, 'image_2', 'full' ) ? ( 'background-image: url('.PG_Blocks_v4::getImageUrl( $args, 'image_2', 'full' ).')' ) : '' ); ?>"></div>
            <div class="md:col-span-2 aspect-[16/9] bg-mist-300 bg-[url('https://images.unsplash.com/photo-1602395714441-e4a5686cbb59?ixid=M3wyMDkyMnwwfDF8c2VhcmNofDE0fHxhcmNoaXRlY3R1cmUlMjB3b29kfGVufDB8fHx8MTc3MzA2NTg0Mnww&ixlib=rb-4.1.0q=85&fm=jpg&crop=faces&cs=srgb&w=1200&h=800&fit=crop')] bg-cover bg-center opacity-0 [animation:fadeInScale_1s_ease-out_forwards] [animation-timeline:view()] [animation-range:entry_0%_entry_40%]" style=";<?php echo ( PG_Blocks_v4::getImageUrl( $args, 'image_wide', 'full' ) ? ( 'background-image: url('.PG_Blocks_v4::getImageUrl( $args, 'image_wide', 'full' ).')' ) : '' ); ?>"></div>
        </div>
    </div>
</section>